Repository lionchat100/lion-chat-fe, pull requests merged in 2025-08, with the labels that each got.

#7 Chore/#3 add required libraries
  package.json
  pages/index.tsx
  pnpm-lock.yaml
  src/app/page.tsx
Labels: Feature

#12 Feat/#9 add shared api config
  src/app/_providers/SocketProvider.tsx
  src/app/_providers/index.ts
  src/app/layout.tsx
  src/shared/api/axios.ts
  src/shared/api/index.ts
  src/shared/api/socket.ts
Labels: Feature

#20 Feat/#14 add entities slice segment
  package.json
  pnpm-lock.yaml
  public/worker.js
  src/app/_providers/SocketProvider.tsx
  src/app/_providers/StompProvider.tsx
  src/app/_providers/index.ts
  src/app/layout.tsx
  src/entities/chat-room/api/getChatRoomList.ts
  src/entities/chat-room/index.ts
  src/entities/chat-room/model/types.ts
  src/entities/chat/index.ts
  src/entities/message/api/getMessageList.ts
  src/entities/message/api/getMoreMessageList.ts
  src/entities/message/index.ts
  src/entities/message/model/types.ts
  src/entities/user/api/getCurrentUser.ts
  src/entities/user/index.ts
  src/entities/user/model/types.ts
  src/shared/api/axios.ts
  src/shared/api/socket.ts
  src/shared/api/stomp.ts
  src/shared/ui/Progress.tsx
  src/views/auth/index.ts
  src/views/chat/index.ts
  src/views/explore/index.ts
  src/views/profile/index.ts
Labels: Feature

#31 Hotfix/#30 login logic fix
  package.json
  public/sw.js
  src/app/(auth)/callback/page.tsx
  src/app/_providers/AuthProvider.tsx
  src/app/_providers/index.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/entities/user/api/getAccessToken.ts
  src/entities/user/api/getOAuthToken.ts
  src/entities/user/api/getUserLogout.ts
  src/entities/user/index.ts
  src/entities/user/model/slice.ts
  src/features/update-user/index.ts
  src/features/update-user/model/newAccessToken.ts
  src/features/update-user/model/userAuthCheck.ts
  src/features/update-user/model/userAuthLogout.ts
  src/features/update-user/model/userOAuthLogin.ts
  src/shared/api/axios.ts
  src/shared/model/auth.ts
  src/views/auth/ui/CallbackPage.tsx
  src/views/setup/ui/SetupPage.tsx
Labels: Hot-Fix, Bug-Fix, Feature

#34 Feat/#32 add global fonts
  package.json
  public/fonts/pretendard/LICENSE.txt
  public/fonts/pretendard/PretendardVariable.woff2
  public/fonts/suite/LICENSE
  public/fonts/suite/SUITE-Variable.woff2
  public/manifest.json
  public/sw.js
  public/workbox-3c9d0171.js
  src/app/globals.css
  src/app/layout.tsx
  src/shared/constants/constant.ts
  src/shared/constants/index.ts
  src/views/auth/ui/CallbackPage.tsx
  src/views/setup/ui/SetupPage.tsx
Labels: Hot-Fix, Bug-Fix, Feature

#40 Feat/#38 message entities features segment
  eslint.config.mjs
  public/sw.js
  src/app/_providers/StompProvider.tsx
  src/entities/chat/api/getChatRoomList.ts
  src/entities/chat/api/getInitChatRoomId.ts
  src/entities/chat/index.ts
  src/entities/chat/model/slice.ts
  src/entities/chat/model/types.ts
  src/entities/message/api/getMessageList.ts
  src/entities/message/api/getMoreMessageList.ts
  src/entities/message/index.ts
  src/entities/message/model/slice.ts
  src/entities/message/model/types.ts
  src/entities/user/model/types.ts
  src/features/update-chat/model/chatSubscription.ts
  src/features/update-message/model/ackMessage.ts
  src/features/update-message/model/loadMessage.ts
  src/features/update-message/model/sendMessage.ts
  src/views/auth/ui/CallbackPage.tsx
Labels: Bug-Fix, Feature

#41 Feat/#25 onboarding step1/2 component
  public/sw.js
  public/workbox-3c9d0171.js
  src/app/layout.tsx
  src/entities/user/api/getOnboardingData.ts
  src/entities/user/lib/onboardingDataMapper.ts
  src/entities/user/model/types.ts
  src/shared/constants/constant.ts
  src/shared/constants/index.ts
  src/shared/ui/Button.tsx
  src/shared/ui/Drawer.tsx
  src/views/auth/ui/OnboardingPage.tsx
  src/widgets/onboarding/index.ts
  src/widgets/onboarding/model/store.ts
  src/widgets/onboarding/model/types.ts
  src/widgets/onboarding/model/validators.ts
  src/widgets/onboarding/ui/DrawerSelect.tsx
  src/widgets/onboarding/ui/OnboardingFunnel.tsx
  src/widgets/onboarding/ui/Step1.tsx
  src/widgets/onboarding/ui/Step1Form.tsx
  src/widgets/onboarding/ui/Step2.tsx
  src/widgets/onboarding/ui/Step2Form.tsx
  src/widgets/onboarding/ui/StepRender.tsx
Labels: Feature

#44 Feat/#42 common component
  src/app/(main)/feed/page.tsx
  src/app/(main)/layout.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/not-found.tsx
  src/entities/user/api/getOnboardingData.ts
  src/shared/ui/Badge.tsx
  src/shared/ui/Button.tsx
  src/widgets/common/NavBar.tsx
  src/widgets/onboarding/ui/Step2Form.tsx
Labels: Feature

#46 Feat/#45 chatroom list page 2
  src/app/(main)/chats/page.tsx
  src/entities/chat/model/types.ts
  src/entities/chat/ui/ChatRoomItem.tsx
  src/entities/message/model/slice.ts
  src/entities/message/model/types.ts
  src/features/update-message/model/loadMessage.ts
  src/views/chat/ui/ChatRoomListPage.tsx
  src/widgets/chat/ui/ChatRoomList.tsx
Labels: Bug-Fix, Feature

#48 hotfix/#26 image multipart 설정 추가
  src/features/update-user/api/uploadImagesList.ts
Labels: Hot-Fix

#49 Feat/#23 chatroom page
  src/app/(main)/chats/[roomId]/page.tsx
  src/entities/chat/index.ts
  src/entities/chat/ui/ChatRoomHeader.tsx
  src/entities/message/index.ts
  src/entities/message/lib/messageGrouping.ts
  src/entities/message/ui/MessageBubble.tsx
  src/features/update-message/index.ts
  src/features/update-message/ui/MessageInput.tsx
  src/views/chat/index.ts
  src/views/chat/ui/ChatRoomPage.tsx
  src/widgets/message/index.ts
  src/widgets/message/ui/MessageScrollArea.tsx
Labels: Bug-Fix, Feature

#52 Hotfix/#26 payload fix
  src/features/update-user/ui/Step1Form.tsx
Labels: Hot-Fix

#53 Hotfix/#51 stomp provider entrypoint hotfix
  src/app/(main)/layout.tsx
  src/app/_providers/StompProvider.tsx
  src/app/layout.tsx
  src/shared/config/GoogleAnalytics.tsx
Labels: Hot-Fix, Feature

#62 Fix/#26 onboarding fix
  src/app/loading.tsx
  src/entities/user/api/getUserProfile.ts
  src/entities/user/lib/onboardingDataMapper.ts
  src/entities/user/lib/validators.ts
  src/entities/user/model/types.ts
  src/features/update-user/model/userOnboarding.ts
  src/features/update-user/ui/DrawerSelect.tsx
  src/features/update-user/ui/ImageUploader.tsx
  src/features/update-user/ui/Step2Form.tsx
  src/features/update-user/ui/Step3Form.tsx
  src/shared/ui/Badge.tsx
  src/shared/ui/Button.tsx
  src/shared/ui/Drawer.tsx
  src/shared/ui/Textarea.tsx
  src/views/auth/ui/OnboardingEndPage.tsx
  src/widgets/onboarding/ui/OnboardingFunnel.tsx
Labels: Feature

#65 Feat/#56 chatroom feature advenced 2
  eslint.config.mjs
  src/app/(main)/chats/[roomId]/page.tsx
  src/app/(main)/chats/page.tsx
  src/app/_providers/StompProvider.tsx
  src/entities/chat/index.ts
  src/entities/chat/model/slice.ts
  src/entities/chat/ui/ChatRoomHeader.tsx
  src/entities/chat/ui/ChatRoomItem.tsx
  src/entities/message/api/getMoreMessageList.ts
  src/entities/message/api/useMessageQuery.ts
  src/entities/message/index.ts
  src/entities/message/lib/messageGrouping.ts
  src/entities/message/model/slice.ts
  src/entities/message/ui/MessageBubble.tsx
  src/entities/message/ui/MessageHeader.tsx
  src/entities/user/index.ts
  src/features/update-chat/index.ts
  src/features/update-chat/lib/pushLiveMessage.ts
  src/features/update-chat/model/chatSubscription.ts
  src/features/update-message/index.ts
  src/features/update-message/lib/messageValidate.ts
  src/features/update-message/model/ackMessage.ts
  src/features/update-message/model/loadMessage.ts
  src/features/update-message/model/sendMessage.ts
  src/features/update-message/ui/MessageInput.tsx
  src/features/update-user/index.ts
  src/shared/api/axios.ts
  src/shared/api/stomp.ts
  src/shared/constants/constant.ts
  src/shared/constants/index.ts
  src/shared/ui/ScrollArea.tsx
  src/views/chat/index.ts
  src/views/chat/ui/ChatRoomListView.tsx
  src/views/chat/ui/ChatRoomPage.tsx
  src/views/chat/ui/ChatRoomView.tsx
  src/widgets/chat/ui/ChatRoomList.tsx
  src/widgets/message/ui/MessageScrollArea.tsx
Labels: Bug-Fix, Feature, Perfomence, Refactoring

#78 Feat/#75 get feed list
  package.json
  pnpm-lock.yaml
  src/app/(main)/feed/page.tsx
  src/entities/comment/model/types.ts
  src/entities/feed/api/getFeedList.ts
  src/entities/feed/libs/buildParams.ts
  src/entities/feed/model/types.ts
  src/entities/feed/ui/FeedHeader.tsx
  src/features/update-comment/ui/Comment.tsx
  src/features/update-feed/api/updateFeedLike.ts
  src/features/update-feed/model/feedLikeToggle.ts
  src/features/update-feed/model/loadFeed.ts
  src/features/update-feed/ui/LikeButton.tsx
  src/features/update-user/api/updateOnboarding.ts
  src/shared/lib/dateUtils.ts
  src/shared/ui/Button.tsx
  src/shared/ui/Tabs.tsx
  src/views/feed/ui/FeedView.tsx
  src/widgets/common/NavBar.tsx
  src/widgets/common/libs/nav.ts
  src/widgets/feed/ui/Feed.tsx
  src/widgets/feed/ui/FeedCard.tsx
  src/widgets/feed/ui/FeedTabPanel.tsx
Labels: Feature

#80 Feat/#77 feed post feature
  src/app/(main)/feed/post/page.tsx
  src/app/_providers/StompProvider.tsx
  src/entities/chat/model/types.ts
  src/entities/chat/ui/ChatRoomItem.tsx
  src/entities/feed/index.ts
  src/entities/feed/ui/FeedPolicyCard.tsx
  src/entities/feed/ui/FeedPostCancelModal.tsx
  src/entities/feed/ui/FeedPostHeader.tsx
  src/entities/message/lib/messageGrouping.ts
  src/entities/message/model/types.ts
  src/entities/message/ui/MessageBubble.tsx
  src/features/update-chat/model/chatSubscription.ts
  src/features/update-feed/api/postFeed.ts
  src/features/update-feed/index.ts
  src/features/update-feed/ui/FeedPostForm.tsx
  src/features/update-feed/ui/PostFeed.tsx
  src/features/update-user/model/userOAuthLogin.ts
  src/shared/api/axios.ts
  src/shared/api/refreshManager.ts
  src/shared/lib/tokenEventBus.ts
  src/views/chat/ui/ChatRoomView.tsx
  src/views/feed/ui/FeedPostView.tsx
Labels: Feature

#86 Feat/#81 minor update 1
  src/entities/user/index.ts
  src/entities/user/lib/clearUserData.ts
  src/entities/user/model/slice.ts
  src/features/update-user/index.ts
  src/features/update-user/model/newAccessToken.ts
  src/features/update-user/model/userAuthCheck.ts
  src/features/update-user/model/userAuthLogout.ts
  src/features/update-user/model/userAutoLogin.ts
  src/features/update-user/model/userOAuthLogin.ts
  src/shared/api/refreshManager.ts
  src/views/auth/ui/CallbackPage.tsx
  src/views/setup/ui/SetupPage.tsx
Labels: Bug-Fix, Feature

#88 Feat/#76 닉네임 체크 로직 추가 및 스타일 변경
  src/app/globals.css
  src/app/layout.tsx
  src/entities/feed/index.ts
  src/entities/feed/ui/FeedFloatingButton.tsx
  src/entities/feed/ui/FeedHeader.tsx
  src/entities/user/lib/onboardingDataMapper.ts
  src/entities/user/lib/validators.ts
  src/entities/user/model/types.ts
  src/features/update-comment/libs/rateLimiter.ts
  src/features/update-comment/model/commentPost.ts
  src/features/update-comment/ui/CommentCard.tsx
  src/features/update-comment/ui/CommentDrawer.tsx
  src/features/update-comment/ui/CommentInput.tsx
  src/features/update-user/api/checkNickname.ts
  src/features/update-user/api/updateOnboarding.ts
  src/features/update-user/model/userNicknameCheck.ts
  src/features/update-user/ui/CheckConfirmDialog.tsx
  src/features/update-user/ui/DrawerSelect.tsx
  src/features/update-user/ui/Step1Form.tsx
  src/features/update-user/ui/Step3Form.tsx
  src/shared/ui/Button.tsx
  src/shared/ui/Drawer.tsx
  src/shared/ui/Select.tsx
  src/shared/ui/Textarea.tsx
  src/views/auth/ui/OnboardingEndPage.tsx
  src/views/feed/ui/FeedPostView.tsx
  src/views/feed/ui/FeedView.tsx
  src/widgets/common/NavBar.tsx
  src/widgets/feed/ui/FeedCard.tsx
  src/widgets/feed/ui/FeedTabPanel.tsx
  src/widgets/onboarding/ui/OnboardingFunnel.tsx
  src/widgets/profile/ProfileCard.tsx
Labels: Bug-Fix, Feature, Refactoring, Quality Assurance

#93 Feat/#91 알림 기능 추가
  public/images/logo/tokit_heart.svg
  public/images/logo/tokit_info.svg
  src/app/(main)/layout.tsx
  src/app/(main)/notify/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/entities/chat/ui/ChatRoomListHeader.tsx
  src/entities/feed/ui/FeedHeader.tsx
  src/entities/notify/api/getNotificationList.ts
  src/entities/notify/libs/notifyDataMapper.ts
  src/entities/notify/model/slice.ts
  src/entities/notify/model/types.ts
  src/entities/notify/ui/NotifyCard.tsx
  src/entities/notify/ui/NotifyHeader.tsx
  src/features/update-comment/ui/CommentDrawer.tsx
  src/features/update-comment/ui/CommentInput.tsx
  src/features/update-notify/model/notificationLoad.ts
  src/features/update-notify/model/useAlarmSubscription.ts
  src/features/update-notify/ui/AlarmSubscriber.tsx
  src/features/update-user/ui/Step1Form.tsx
  src/features/update-user/ui/Step3Form.tsx
  src/shared/model/useKeyBoardOffset.ts
  src/shared/ui/Input.tsx
  src/shared/ui/LoadingSpinner.tsx
  src/views/auth/ui/OnboardingEndPage.tsx
  src/views/notify/ui/NotifyView.tsx
  src/widgets/common/NavShell.tsx
  src/widgets/common/NotificationBell.tsx
  src/widgets/explore/ExploreHeader.tsx
  src/widgets/feed/ui/Feed.tsx
  src/widgets/feed/ui/FeedCard.tsx
  src/widgets/feed/ui/FeedTabPanel.tsx
  src/widgets/notify/ui/NorifyList.tsx
  src/widgets/onboarding/ui/OnboardingFunnel.tsx
  src/widgets/profile/ProfileHeader.tsx
Labels: Bug-Fix, Feature

#94 Feat/#76 온보딩 유효성 이슈 수정
  src/app/(main)/feeds/page.tsx
  src/app/(main)/feeds/post/page.tsx
  src/entities/feed/ui/FeedFloatingButton.tsx
  src/entities/feed/ui/FeedPolicyCard.tsx
  src/entities/feed/ui/FeedPostHeader.tsx
  src/entities/notify/libs/notifyDataMapper.ts
  src/entities/user/lib/validators.ts
  src/entities/user/model/types.ts
  src/features/update-feed/ui/FeedPostForm.tsx
  src/features/update-user/model/userOnboarding.ts
  src/features/update-user/ui/DrawerSelect.tsx
  src/features/update-user/ui/Step1Form.tsx
  src/features/update-user/ui/Step2Form.tsx
  src/views/feed/ui/FeedPostView.tsx
  src/widgets/common/NavShell.tsx
  src/widgets/common/libs/nav.ts
Labels: Bug-Fix, Quality Assurance

#97 hotfix/#68 댓글 드로우 높이 수정
  src/features/update-comment/ui/CommentDrawer.tsx
Labels: Hot-Fix

#101 Feat/#98 like profile feature
  public/icons/android-chrome-192x192.png
  public/icons/android-chrome-512x512.png
  public/icons/apple-touch-icon.png
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon.ico
  public/icons/og-image.png
  public/images/logo/tokit_landing.png
  src/app/(main)/profile/[id]/page.tsx
  src/app/favicon.ico
  src/features/update-user/index.ts
  src/features/update-user/model/userLikeProfile.ts
  src/features/update-user/ui/ProfileLikeButton.tsx
  src/views/explore/ExploreView.tsx
  src/views/setup/ui/SetupPage.tsx
  src/widgets/profile/OtherProfileCard.tsx
  src/widgets/profile/ProfileActionButtons.tsx
Labels: Bug-Fix, Feature, Perfomence, Quality Assurance

#107 fix/#102 온보딩 유효성 검증 이슈 수정
  src/app/(auth)/onboarding/page.tsx
  src/app/globals.css
  src/entities/user/lib/validators.ts
  src/features/update-user/model/userImageUpload.ts
  src/features/update-user/ui/ImageUploader.tsx
  src/features/update-user/ui/Step1Form.tsx
  src/features/update-user/ui/Step2Form.tsx
  src/shared/constants/constant.ts
Labels: Bug-Fix

#111 Fix/#68 common design error
  middleware.ts
  public/images/icon_kakao.svg
  public/images/logo/tokit_error.svg
  public/images/logo/tokit_heart.svg
  public/images/logo/tokit_hold.svg
  public/images/logo/tokit_landing.png
  public/images/logo/tokit_landing.svg
  public/images/logo/tokit_loading2.svg
  src/app/(auth)/callback/page.tsx
  src/app/(auth)/onboarding/page.tsx
  src/app/(main)/chats/[roomId]/page.tsx
  src/app/(main)/chats/page.tsx
  src/app/(main)/profile/[id]/page.tsx
  src/app/(main)/profile/page.tsx
  src/app/globals.css
  src/app/loading.tsx
  src/entities/chat/ui/ChatRoomListHeader.tsx
  src/entities/feed/ui/FeedFloatingButton.tsx
  src/features/update-comment/ui/CommentDrawer.tsx
  src/features/update-user/ui/Step1Form.tsx
  src/views/auth/ui/CallbackPage.tsx
  src/views/explore/ExploreView.tsx
  src/views/profile/ui/EditProfileView.tsx
  src/views/profile/ui/LikeProfilesView.tsx
  src/views/setup/ui/SetupPage.tsx
  src/widgets/chat/ui/ChatRoomList.tsx
  src/widgets/common/FallbackScreen.tsx
  src/widgets/feed/ui/FeedTabPanel.tsx
  src/widgets/onboarding/ui/OnboardingFunnel.tsx
  src/widgets/profile/OtherProfileHeader.tsx
Labels: Bug-Fix, Quality Assurance

#147 Fix/#134 수정사항 반영..
  src/app/layout.tsx
  src/views/profile/ui/EditProfileViewTest.tsx
  src/widgets/form/DrawerSelectTest.tsx
  src/widgets/message/ui/MessageScrollArea.tsx
  src/widgets/onboarding/ui/OnboardingFunnel.tsx
Labels: Hot-Fix

#149 Fix/#148 layout 수정
  src/views/chat/ui/ChatRoomView.tsx
  src/views/profile/ui/EditProfileViewTest.tsx
  src/widgets/message/ui/MessageScrollArea.tsx
  src/widgets/profile/ProfileHeader.tsx
Labels: Bug-Fix

#150 Hotfix/#145 vercel image optimization issue
  next.config.ts
  src/entities/user/ui/LikeProfileCard.tsx
  src/features/update-message/ui/MessageInput.tsx
  src/widgets/profile/ImageSlider.tsx
  src/widgets/profile/OtherProfileCard.tsx
  src/widgets/profile/ProfileCard.tsx
  src/widgets/profile/ProfileEditButton.tsx
  src/widgets/profile/ProfileSidebar.tsx
Labels: Hot-Fix, Perfomence

#155 docs/#154 readme 초안 추가
  README.md
Labels: Document
